version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: rohitraj1996/reverseproxy:"$VERSION"
  backend_user:
    build:
      context: ../udagram-api-user
    image: rohitraj1996/udagram-api-user:"$VERSION"
  backend_feed:
    build:
      context: ../udagram-api-feed
    image: rohitraj1996/udagram-api-feed:"$VERSION"
  frontend:
    build:
      context: ../udagram-frontend
    image: rohitraj1996/udagram-frontend:local